### ISSUE TITLE
Token Authorization Doesn't Work on Docker

### ISSUE THREAD

**Issue by margot-l** [JBEI/jqmm#6]
Hi,
I've been trying to get jQMM to work. I've tried the Docker installation route and the straight up downloading from GitHub. With Docker, I get as far as opening jqmm after installing gams and then get a token to C+P into my browser. But when I do, it just takes me to the default Jupyter home and doesn't otherwise seem to finish the jqmm installation. Next I tried to just download the repository from GitHub. This works better and I can at least open the Jupyter files but now I can't access GAMS from the command line (even though I've downloaded it). Any ideas for how to solve this? I know that you might not be able to do anything about Docker but is there a way for me to install GAMS properly or to modify the code so that it can access GAMS from the command line without using Docker?
Thanks,
Margot

**Comment by TylerBackman** [comment]
Hi Margot, can you clarify what you are seeing after opening Jupyter with the Docker install? When you say you are taken to a "default Jupyter home" does that mean you are not seeing any files listed in Jupyter? 

Sincerely,
Tyler

**Comment by TylerBackman** [comment]
Here is what it is supposed to look like:
<img width="793" alt="jqmm" src="https://cloud.githubusercontent.com/assets/647482/25407773/7327f48e-29c0-11e7-937f-105c90c33ada.png">

**Comment by margot-l** [comment]
Here's what mine looks like after CPing the token: <img width="1180" alt="jupyter home" src="https://cloud.githubusercontent.com/assets/15984874/25408599/a706eeb0-29dc-11e7-8f2f-5f97b6fe147f.png">

In addition, in terminal, the operation doesn't register as having used up the token.

**Comment by TylerBackman** [comment]
It looks like it's showing your home directory on your host computer. Coupled with the fact that you're not seeing any log of the token being used, could you already have a jupyter server running on your computer, from some other program that is using up the port?

I recommend removing your jQMM container, and restarting it on a new port.

First stop and remove your jQMM container like this:
```
docker stop jqmm
docker rm jqmm
```

Then run the instructions again, but change the port to 8889 instead of 8888 in step 1:

`docker run --name jqmm -p 8889:8888 -d mhgarci1/jqmm`

Then when you get your token url, change it slightly in the browser to go to :8889 instead of :8888, although the command line will still say it is using 8888. Please let me know if this works.
